config/routes.rb
Contest4good::Application.routes.draw do

  devise_for :admins,
             :controllers => {:sessions => "a/sessions", :invitations => "a/invitations"},
             :path => 'a',
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             skip: [:registration, :password]

  devise_for :users,
             :controllers => {:sessions => "u/sessions", :invitations => "u/invitations"},
             :path => 'u',
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             skip: [:registration, :password]

  namespace :u do
    resource :user_profile, :controller => "user_profiles", only: [:edit, :update, :show]
    get '/', to: 'home#index', as: 'home'
  end

  namespace :a do
    resource :admin_profile, :controller => "admin_profiles", only: [:edit, :update, :show]
    resources :admin_profiles, :controller => "admin_profiles", only: [:index]
    get '/', to: 'home#index', as: 'home'
    resources :contests
  end


  get "home/index"
  root :to => "home#index"
end

app/controllers/u/application_controller.rb
class U::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  layout "u/application"

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :roles => []) }
  end

end

app/controllers/u/home_controller.rb
class U::HomeController < U::ApplicationController
  def index
  end
end

app/controllers/u/invitations_controller.rb
class U::InvitationsController < Devise::InvitationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/invitation/new
  def new
    self.resource = resource_class.new
    #resource.build_user_profile
    render :new
  end

  def update
    attributes = params[:user]
    original_token = attributes.delete(:invitation_token)
    self.resource = User.find_by_invitation_token(original_token, false)
    if resource.errors.empty?
      resource.build_user_profile(attributes[:user_profile_attributes])
      resource.assign_attributes(attributes)
    end

    if resource.valid? && resource.user_profile.valid?
      begin
        resource.user_profile.save!
        resource.accept_invitation!
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message :notice, flash_message
        sign_in(resource_name, resource)
        respond_with resource, :location => u_home_path
      rescue
        respond_with_navigational(resource) { render :edit }
      end
    else
      respond_with_navigational(resource) { render :edit }
    end
  end

  def edit
    resource.invitation_token = params[:invitation_token]
    resource.build_user_profile
    render :edit
  end

  protected
  def configure_permitted_parameters
    # Only add some parameters
    devise_parameter_sanitizer.for(:accept_invitation).concat [:user_profile_attributes]
  end

  private
  def resource_params
    params.permit(user: [:name, :email, :invitation_token, :user_profile_attributes])[:user]
  end

  # this is called when accepting invitation
  # should return an instance of resource class
  def accept_resource
    resource_class.accept_invitation!(update_resource_params)
    resource
  end

end

app/controllers/u/sessions_controller.rb
class U::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(user)
    u_home_path
  end
end

app/controllers/u/user_profiles_controller.rb
class U::UserProfilesController < U::ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /u/user_profile
  # GET /u/user_profile.json
  def show
  end

  # GET /u/user_profile/edit
  def edit
  end

  # PATCH/PUT /u/user_profile
  # PATCH/PUT /u/user_profile.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to u_home_path, notice: I18n.t('u.user_profiles.notices.update') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /u/user_profile
  # DELETE /u/user_profile.json
  #def destroy
  #  @user_profile.destroy
  #  respond_to do |format|
  #    format.html { redirect_to u_user_profiles_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = current_user.user_profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :first_name, :middle_name, :last_name, :born_on, :address, :school, :grade, :phone, :parent_name, :parent_phone)
    end
end

app/helpers/u/home_helper.rb
module U::HomeHelper
end

app/views/layouts/u/_menu.slim
nav.navbar.navbar-default role="navigation"
  .navbar-header
    button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to u_home_path, class:'navbar-brand' do
      i.glyphicon.glyphicon-question-sign
      '
      = app_title

  .collapse.navbar-collapse.navbar-ex1-collapse
    ul.nav.navbar-nav
      /li.active
      li
        = link_to t('menu.home'), u_home_path
    ul.nav.navbar-nav.navbar-right
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#"
          span.user-info
            i.glyphicon.glyphicon-user
            small #{current_user.user_profile.first_name}
          b.caret
        ul.dropdown-menu
          li
            = link_to edit_u_user_profile_path(current_user) do
              span= t('activerecord.models.user_profile')
          li.divider
          li.logout
            = link_to "<i class=\"icon-off\"></i> #{t('menu.sign_out')}".html_safe, destroy_user_session_path, method: :get
  /! /.navbar-collapse

app/views/layouts/u/application.html.slim
doctype 5
html(lang="en")
  head
    =render 'layouts/header'
  body
    = render 'layouts/u/menu'
    .container
      .main-container#main-container
        .main-container-inner
          .main-content
            = render 'layouts/messages'
            /#breadcrumbs.breadcrumbs
              ul.breadcrumb
                li
                  i.glyphicon.glyphicon-home
                  =link_to t('main_menu.home'),root_path
                -@breadcrumb.each_with_index do |b,i|
                  -unless b[:name].nil?
                    li class=(i+1 == @breadcrumb.size ? 'active':'')
                      -unless b[:url].empty?
                        =link_to b[:name],b[:url]
                      -else
                        =b[:name]

            .page-content
              = yield
    footer
      hr
      p.text-center
        small
          = link_to root_path do
            /i.glyphicon.glyphicon-pen
            ' &nbsp;#{app_title}
    /!
      | Javascripts
      | \==================================================
    /! Placed at the end of the document so the pages load faster
    = yield(:page_javascript) if content_for?(:page_javascript)