config/routes.rb
Contest4good::Application.routes.draw do

  devise_for :admins,
             :controllers => {:sessions => "a/sessions", :invitations => "a/invitations"},
             :path => 'a',
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             skip: [:registration, :password]

  devise_for :users,
             :controllers => {:sessions => "u/sessions", :invitations => "u/invitations"},
             :path => 'u',
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             skip: [:registration, :password]

  namespace :u do
    resource :user_profile, :controller => "user_profiles", only: [:edit, :update, :show]
    get '/', to: 'home#index', as: 'home'
  end

  namespace :a do
    resource :admin_profile, :controller => "admin_profiles", only: [:edit, :update, :show]
    resources :admin_profiles, :controller => "admin_profiles", only: [:index]
    get '/', to: 'home#index', as: 'home'
    resources :contests
  end


  get "home/index"
  root :to => "home#index"
end

app/views/admins/shared/_links.slim
- if controller_name != 'sessions'
  = link_to t('menu.sign_in'), new_admin_session_path
  br
= link_to t('menu.sign_up'), new_admin_invitation_path
br
/- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
/- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_admin_confirmation_path
  br
/- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_admin_unlock_path
  br
/- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    br