config/routes.rb
Contest4good::Application.routes.draw do

  devise_for :admins,
             :controllers => {:sessions => "a/sessions", :invitations => "a/invitations"},
             :path => 'a',
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             skip: [:registration, :password]

  devise_for :users,
             :controllers => {:sessions => "u/sessions", :invitations => "u/invitations"},
             :path => 'u',
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             skip: [:registration, :password]

  namespace :u do
    resource :user_profile, :controller => "user_profiles", only: [:edit, :update, :show]
    get '/', to: 'home#index', as: 'home'
  end

  namespace :a do
    resource :admin_profile, :controller => "admin_profiles", only: [:edit, :update, :show]
    resources :admin_profiles, :controller => "admin_profiles", only: [:index]
    get '/', to: 'home#index', as: 'home'
    resources :contests
  end


  get "home/index"
  root :to => "home#index"
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user

  attr_accessible :first_name, :middle_name, :last_name, :born_on, :address, :school, :grade, :phone,
                  :parent_name, :parent_phone, :created_at, :updated_at, :user_id, :terms
  attr_accessor :terms

  validates :first_name, :middle_name, :last_name, :born_on, :address, :school, :grade, :phone,
            :parent_name, :parent_phone, presence: {message: I18n.t("errors.messages.blank")}

  # this validation is on only for invitation/edit
  # it's off when updating user_profile
  # TODO validates :terms, :acceptance => true
  validates :terms, presence: {message: I18n.t("errors.messages.accept_terms")}, on: :create
end

app/controllers/u/application_controller.rb
class U::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  layout "u/application"

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :roles => []) }
  end

end

app/controllers/u/home_controller.rb
class U::HomeController < U::ApplicationController
  def index
  end
end

app/controllers/u/invitations_controller.rb
class U::InvitationsController < Devise::InvitationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/invitation/new
  def new
    self.resource = resource_class.new
    #resource.build_user_profile
    render :new
  end

  def update
    attributes = params[:user]
    original_token = attributes.delete(:invitation_token)
    self.resource = User.find_by_invitation_token(original_token, false)
    if resource.errors.empty?
      resource.build_user_profile(attributes[:user_profile_attributes])
      resource.assign_attributes(attributes)
    end

    if resource.valid? && resource.user_profile.valid?
      begin
        resource.user_profile.save!
        resource.accept_invitation!
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message :notice, flash_message
        sign_in(resource_name, resource)
        respond_with resource, :location => u_home_path
      rescue
        respond_with_navigational(resource) { render :edit }
      end
    else
      respond_with_navigational(resource) { render :edit }
    end
  end

  def edit
    resource.invitation_token = params[:invitation_token]
    resource.build_user_profile
    render :edit
  end

  protected
  def configure_permitted_parameters
    # Only add some parameters
    devise_parameter_sanitizer.for(:accept_invitation).concat [:user_profile_attributes]
  end

  private
  def resource_params
    params.permit(user: [:name, :email, :invitation_token, :user_profile_attributes])[:user]
  end

  # this is called when accepting invitation
  # should return an instance of resource class
  def accept_resource
    resource_class.accept_invitation!(update_resource_params)
    resource
  end

end

app/controllers/u/sessions_controller.rb
class U::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(user)
    u_home_path
  end
end

app/controllers/u/user_profiles_controller.rb
class U::UserProfilesController < U::ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /u/user_profile
  # GET /u/user_profile.json
  def show
  end

  # GET /u/user_profile/edit
  def edit
  end

  # PATCH/PUT /u/user_profile
  # PATCH/PUT /u/user_profile.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to u_home_path, notice: I18n.t('u.user_profiles.notices.update') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /u/user_profile
  # DELETE /u/user_profile.json
  #def destroy
  #  @user_profile.destroy
  #  respond_to do |format|
  #    format.html { redirect_to u_user_profiles_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = current_user.user_profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :first_name, :middle_name, :last_name, :born_on, :address, :school, :grade, :phone, :parent_name, :parent_phone)
    end
end

app/helpers/u/home_helper.rb
module U::HomeHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/u/user_profiles/_form.html.slim
= simple_form_for(@user_profile, url: u_user_profile_path) do |f|
  = f.error_notification
  .row
    .col-sm-6
      h3= t('.main_info')
      = f.input :last_name
      = f.input :first_name
      = f.input :middle_name
      = f.input :born_on, as: :date,
                start_year: Date.today.year - 20,
                end_year: Date.today.year - 12,
                discard_day: false,
                order: [:day, :month, :year]
      hr
      h3= t('.contacts')
      = f.input :address
      = f.input :phone
      hr
      h3= t('.study_place')
      = f.input :school
      = f.input :grade
    .col-sm-6
      h3= t('.parent_info')
      = f.input :parent_name
      = f.input :parent_phone
  .form-group
    = f.button :submit, data: { disable_with: t('shared.please_wait')}

app/views/u/user_profiles/edit.html.slim
h1= t('.title')

== render 'form'

= link_to 'Back', u_home_path, class: 'btn btn-default'

app/views/u/user_profiles/index.html.slim
h1 Listing user_profiles

table
  tr
    th User
    th First name
    th Middle name
    th Last name
    th Born on
    th Address
    th School
    th Grade
    th Phone
    th Parent name
    th Parent phone
    th
    th

  - @user_profiles.each do |user_profile|
    tr
      td = user_profile.user
      td = user_profile.first_name
      td = user_profile.middle_name
      td = user_profile.last_name
      td = user_profile.born_on
      td = user_profile.address
      td = user_profile.school
      td = user_profile.grade
      td = user_profile.phone
      td = user_profile.parent_name
      td = user_profile.parent_phone
      td = link_to 'Show', user_profile
      td = link_to 'Edit', edit_user_profile_path(user_profile)

app/views/u/user_profiles/show.html.slim
p#notice = notice

p
  strong User:
  = @user_profile.user
p
  strong First name:
  = @user_profile.first_name
p
  strong Middle name:
  = @user_profile.middle_name
p
  strong Last name:
  = @user_profile.last_name
p
  strong Born on:
  = @user_profile.born_on
p
  strong Address:
  = @user_profile.address
p
  strong School:
  = @user_profile.school
p
  strong Grade:
  = @user_profile.grade
p
  strong Phone:
  = @user_profile.phone
p
  strong Parent name:
  = @user_profile.parent_name
p
  strong Parent phone:
  = @user_profile.parent_phone

= link_to 'Edit', edit_user_profile_path(@user_profile)
'|
= link_to 'Back', user_profiles_path